description: Returns a socket url to the matched channel
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ws/url
execution:
    timeout: 10s
    memory: 10MB
    call: getsocketurl
